import { pushNewTune } from '../../firebase';

if (confirm("Do you really want to do this?")) {
    [
     {
       "flags": "🌙⚜️",
       "name": "Gateau aux Bananes",
       "type": "reel",
       "musicKey": "C",
       "era": "",
       "composer": "Michel Bordeleau",
       "stage": "drill",
       "dateLearnt": "Sept 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "La fée des dents / The Tooth Fairy Jig",
       "type": "Jig",
       "musicKey": "G",
       "era": "Contemporary",
       "composer": "André Brunet",
       "stage": "drill",
       "dateLearnt": "Sept 2017",
       "video": "André Brunet",
       "video2": "",
       "source": "André Brunet",
       "dots": "",
       "sessions": "Quebecois",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "Maison de Glace",
       "type": "Jig",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Sept 2017",
       "video": "André Brunet",
       "video2": "",
       "source": "André Brunet",
       "dots": "",
       "sessions": "Quebecois",
       "notes": ""
     },
     {
       "flags": "🌙",
       "name": "Earl of Dalhousie's Happy Return to Scotland",
       "type": "March",
       "musicKey": "D",
       "era": "",
       "composer": "Neil Gow Junior",
       "stage": "perform",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - Alasdair",
       "dots": "https://thesession.org/tunes/1867",
       "sessions": "",
       "notes": "dont staccato"
     },
     {
       "flags": "🌙",
       "name": "Cuillean Nights",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "Alasdair Fraser",
       "stage": "perform",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - Alasdair",
       "dots": "https://thesession.org/tunes/8318",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙",
       "name": "Cuillean of Rhum",
       "type": "Air",
       "musicKey": "G?",
       "era": "",
       "composer": "",
       "stage": "embellish",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - Alasdair",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙",
       "name": "Glenfinnan Nights",
       "type": "March",
       "musicKey": "",
       "era": "contemp",
       "composer": "Alasdair Fraser",
       "stage": "perform",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - Alasdair",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙",
       "name": "Fonix",
       "type": "7 dance",
       "musicKey": "A",
       "era": "contemp",
       "composer": "Annbjorg Lien",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - Alasdair",
       "dots": "",
       "sessions": "",
       "notes": "phoenix"
     },
     {
       "flags": "🌙⚜️",
       "name": "Le bateau à roue",
       "type": "reel",
       "musicKey": "G",
       "era": "contemp",
       "composer": "André Brunet",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Garde ton souffle",
       "type": "reel",
       "musicKey": "A",
       "era": "contemp",
       "composer": "André Brunet",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Salle de lavage",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "Éric Beaudry",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Jos Louis",
       "type": "reel",
       "musicKey": "A",
       "era": "",
       "composer": "Michel Bordeleau",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Reel du Brae",
       "type": "reel",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "http://tunearch.org/wiki/Reel_du_Brae",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "La Soiree Chez Alcide",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "Thérèse Rioux",
       "stage": "drill",
       "dateLearnt": "Sept 2017",
       "video": "André Brunet",
       "video2": "",
       "source": "André Brunet",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "Le Cotillon de la Mariée",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Sept 2017",
       "video": "",
       "video2": "",
       "source": "Lisa Ornstein",
       "dots": "",
       "sessions": "",
       "notes": "Édouard Richard"
     },
     {
       "flags": "⚜️",
       "name": "Reel des Vieux",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Sept 2017",
       "video": "",
       "video2": "",
       "source": "Lisa Ornstein",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙",
       "name": "Behind the Waterfall",
       "type": "reel",
       "musicKey": "Dm",
       "era": "contemp",
       "composer": "Jess Newman",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - Jess",
       "dots": "",
       "sessions": "",
       "notes": "named after a zelda character!"
     },
     {
       "flags": "",
       "name": "Hunting the Squirrel",
       "type": "Jig",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "The Gloaming",
       "video2": "",
       "source": "The Gloaming",
       "dots": "https://thesession.org/tunes/3333",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🕒",
       "name": "Bucks of Oranmore",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "August 2017",
       "video": "Bothy Band",
       "video2": "Martin Hayes",
       "source": "Bothy Band",
       "dots": "",
       "sessions": "",
       "notes": "apparently overplayed in sessions? 5 parts tho!"
     },
     {
       "flags": "🕒",
       "name": "Allistrum's March",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "embellish",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/2136",
       "sessions": "",
       "notes": "meet it at speed"
     },
     {
       "flags": "🕒",
       "name": "Cock and the Hen",
       "type": "Slipjig",
       "musicKey": "Bm",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/93",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🔥",
       "name": "Cottage Groves",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/1272",
       "sessions": "",
       "notes": "supposedly a very old tune"
     },
     {
       "flags": "🕒",
       "name": "Glen of Aherlow aka Lafferty's",
       "type": "reel",
       "musicKey": "Ed",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/496",
       "sessions": "Susan Burke",
       "notes": "dont forget to play the B part twice"
     },
     {
       "flags": "",
       "name": "John Ryan's Polka",
       "type": "Polka",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/441",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Lucy Farr's",
       "type": "Barndance",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/1307",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Split Rock",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "Kevin Burke",
       "stage": "drill",
       "dateLearnt": "August 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/2861",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Carraroe",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "July 2017",
       "video": "",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/771",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🔥",
       "name": "Gallagher's Frolics",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "July 2017",
       "video": "Martin Hayes",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/160",
       "sessions": "",
       "notes": "Martin's set: Tell Her / Gallagher's"
     },
     {
       "flags": "⭐🔥",
       "name": "Gathering of the Clans",
       "type": "Hornpipe",
       "musicKey": "D",
       "era": "",
       "composer": "it me",
       "stage": "drill",
       "dateLearnt": "July 2017",
       "video": "",
       "video2": "",
       "source": "it me",
       "dots": "Noteflight",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🕒",
       "name": "Holly Bush",
       "type": "reel",
       "musicKey": "Amix",
       "era": "",
       "composer": "Finbarr Dwyer",
       "stage": "drill",
       "dateLearnt": "July 2017",
       "video": "Martin Hayes",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/1566",
       "sessions": "",
       "notes": "Part of that epic martin/cahill set, towards the end (24m27s)"
     },
     {
       "flags": "🕒",
       "name": "Rakish Paddy",
       "type": "reel",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "July 2017",
       "video": "Martin Hayes",
       "video2": "Altan",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/86",
       "sessions": "",
       "notes": "Part of that epic martin/cahill set, towards the end (21m24s)"
     },
     {
       "flags": "🕒",
       "name": "Ship in Full Sail",
       "type": "Jig",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "July 2017",
       "video": "",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/261",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Tell Her I Am",
       "type": "Jig",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "July 2017",
       "video": "",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/161",
       "sessions": "",
       "notes": "Martin's set: Tell Her / Gallagher's"
     },
     {
       "flags": "⭐🕒",
       "name": "Blackbird",
       "type": "Set Dance",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Finn Magill",
       "dots": "https://thesession.org/tunes/1104",
       "sessions": "",
       "notes": "The second of Kevin's \"The Blackbird (Two Versions)\""
     },
     {
       "flags": "🔥",
       "name": "Drunken Landlady",
       "type": "reel",
       "musicKey": "Em/Am",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Bothy Band",
       "video2": "",
       "source": "Bothy Band",
       "dots": "https://thesession.org/tunes/363#setting13165",
       "sessions": "",
       "notes": "play it on a low string; Bothy Band does it in Am"
     },
     {
       "flags": "",
       "name": "Dusty Windowsills",
       "type": "Jig",
       "musicKey": "Ad",
       "era": "",
       "composer": "Johnny Harling",
       "stage": "enhance",
       "dateLearnt": "June 2017",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/29",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🔥",
       "name": "Earl's Chair",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/221",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Green Fields of Glentown",
       "type": "reel",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "June 2017",
       "video": "Finn Magill",
       "video2": "",
       "source": "Finn Magill",
       "dots": "https://thesession.org/tunes/671",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Humors of Trim",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "June 2017",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/88",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Hunter's Purse",
       "type": "reel",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/283",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "King of the Pipers",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "June 2017",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/54",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Langstrom's Pony",
       "type": "Jig",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/61",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Lord Mayo",
       "type": "March",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Lunasa",
       "video2": "",
       "source": "Lunasa",
       "dots": "https://thesession.org/tunes/638",
       "sessions": "",
       "notes": "1st of Eanair bu Lunasa"
     },
     {
       "flags": "🕒",
       "name": "Maids of Mt. Kisco",
       "type": "reel",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Lunasa",
       "video2": "",
       "source": "Joan Maybank",
       "dots": "https://thesession.org/tunes/432",
       "sessions": "",
       "notes": "3rd of Eanair bu Lunasa; not to be confused with Sporting Paddy"
     },
     {
       "flags": "",
       "name": "Mooncoin",
       "type": "Jig",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "June 2017",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/206",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🔥🕒",
       "name": "Mountain Road",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "Michael Gorman",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/68",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Sporting Paddy",
       "type": "reel",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "June 2017",
       "video": "",
       "video2": "",
       "source": "Joan Maybank",
       "dots": "https://thesession.org/tunes/430",
       "sessions": "",
       "notes": "Not to be confused with Maids of Mt Kisco"
     },
     {
       "flags": "",
       "name": "Toss the Feathers",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "June 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/113",
       "sessions": "Susan Burke?",
       "notes": "Sligo version?"
     },
     {
       "flags": "⭐",
       "name": "A Long Night on the Misty Moor",
       "type": "Air",
       "musicKey": "",
       "era": "",
       "composer": "Liz Carroll",
       "stage": "perform",
       "dateLearnt": "May 2017",
       "video": "",
       "video2": "",
       "source": "Liz Carroll",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🔥",
       "name": "An raibh tu ag an gCarraig?",
       "type": "Air",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Brian Conway",
       "video2": "Seamus Ennis (Pipes)",
       "source": "Brian Conway",
       "dots": "https://thesession.org/tunes/9695",
       "sessions": "",
       "notes": "Were You at the Rock? (mass rock) Pr: Un row too egg un gairig?"
     },
     {
       "flags": "",
       "name": "Banks of the Suir",
       "type": "Air",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🔥",
       "name": "Beare Island Reel",
       "type": "reel",
       "musicKey": "Ed",
       "era": "",
       "composer": "Finbar Dwyer",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/696",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Captain, The ",
       "type": "Waltz",
       "musicKey": "",
       "era": "",
       "composer": "Hanneke Cassel",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Hanneke Cassel",
       "video2": "",
       "source": "Hanneke Cassel",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Flowers of Spring",
       "type": "Jig",
       "musicKey": "Dm",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/1283#setting21344",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Granny's Bonnet",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "May 2017",
       "video": "Fergal Scahill",
       "video2": "",
       "source": "Fergall Scahill",
       "dots": "Noteflight",
       "sessions": "",
       "notes": "Written after gardening with his mam at his new house"
     },
     {
       "flags": "",
       "name": "Her Long Dark Hair Flowing Down Her Back",
       "type": "Hornpipe",
       "musicKey": "D",
       "era": "",
       "composer": "Junior Crehan",
       "stage": "enhance",
       "dateLearnt": "May 2017",
       "video": "Fergal Scahill",
       "video2": "",
       "source": "Fergal Scahill",
       "dots": "https://thesession.org/tunes/1263",
       "sessions": "",
       "notes": "\"Hair color changes depending on which of the composer's daughters is present\""
     },
     {
       "flags": "",
       "name": "Jer The Rigger",
       "type": "Polka",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Martin Hayes",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/1367",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Julia Delaney",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "embellish",
       "dateLearnt": "May 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/589",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "⭐🔥",
       "name": "Laington's Reel",
       "type": "reel",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/1420",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🔥",
       "name": "Mason's Apron",
       "type": "reel",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/74",
       "sessions": "",
       "notes": "Scottish tune? irish style? not Mason's Apron, but Micho Russell's?"
     },
     {
       "flags": "⭐",
       "name": "Morning Dew, The ",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/69",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "New Mown Meadow",
       "type": "reel",
       "musicKey": "Ed",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "May 2017",
       "video": "Fergal Scahill",
       "video2": "",
       "source": "Fergall Scahill",
       "dots": "https://thesession.org/tunes/2706",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Oak Tree Reel",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "May 2017",
       "video": "Fergal Scahill",
       "video2": "",
       "source": "Fergall Scahill",
       "dots": "https://thesession.org/tunes/212",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Rolling in the Barrel",
       "type": "reel",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "May 2017",
       "video": "Martin Hayes",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/500",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Swallow's Tail Reel",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "May 2017",
       "video": "Dervish",
       "video2": "Fergal Scahill",
       "source": "Fergal Scahill",
       "dots": "https://thesession.org/tunes/105",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🔥",
       "name": "Tuttles",
       "type": "reel",
       "musicKey": "Dd",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/528",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Twilight In Portroe",
       "type": "reel",
       "musicKey": "A",
       "era": "50s-80s",
       "composer": "Sean Ryan",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "Fergal Scahill",
       "video2": "De Danann",
       "source": "Fergal Scahill",
       "dots": "https://thesession.org/tunes/4091",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Woman of the House",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "May 2017",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/321",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Moving Pint",
       "type": "Hornpipe",
       "musicKey": "G",
       "era": "",
       "composer": "Charlie Lennon",
       "stage": "enhance",
       "dateLearnt": "April 2017",
       "video": "",
       "video2": "",
       "source": "Fergal Scahill",
       "dots": "https://thesession.org/tunes/3063",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Si Bheag, Si Mhor",
       "type": "Air",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "April 2017",
       "video": "",
       "video2": "",
       "source": "Fergal Scahill",
       "dots": "https://thesession.org/tunes/449",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Silver Spear",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "April 2017",
       "video": "",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/182",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Sweeney's Buttermilk",
       "type": "reel",
       "musicKey": "Bm",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "April 2017",
       "video": "Fergal Scahill",
       "video2": "",
       "source": "Fergall Scahill",
       "dots": "https://thesession.org/tunes/556",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "An Paistin Fionn",
       "type": "Hornpipe",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "embellish",
       "dateLearnt": "March 2017",
       "video": "",
       "video2": "",
       "source": "Dervish",
       "dots": "https://thesession.org/tunes/5675",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Battle of Aughrim, The",
       "type": "Hornpipe",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "embellish",
       "dateLearnt": "March 2017",
       "video": "",
       "video2": "",
       "source": "Mary McNamara",
       "dots": "https://thesession.org/tunes/1308",
       "sessions": "",
       "notes": "Different version from Susan Burke crowd"
     },
     {
       "flags": "",
       "name": "Beauties of Autumn",
       "type": "Hornpipe",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "March 2017",
       "video": "",
       "video2": "",
       "source": "Dervish",
       "dots": "https://thesession.org/tunes/4553",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Breton Gavottes",
       "type": "Gavotte",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "March 2017",
       "video": "",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Da Slockit Light",
       "type": "Air",
       "musicKey": "D",
       "era": "",
       "composer": "Tom Anderson",
       "stage": "perform",
       "dateLearnt": "Feb 2017",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/1863",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Kerfunken Jig",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "Feb 2017",
       "video": "",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/139",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Lucy Campbell's",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Feb 2017",
       "video": "",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/1552",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Paddy Fahey’s",
       "type": "Jig",
       "musicKey": "Gm",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Feb 2017",
       "video": "",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Along the Western Shore",
       "type": "Strathspey",
       "musicKey": "D",
       "era": "",
       "composer": "Paul Machlis",
       "stage": "enhance",
       "dateLearnt": "Jan 2017",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Eternal Friendship",
       "type": "Air",
       "musicKey": "A",
       "era": "",
       "composer": "Phil Cunningham",
       "stage": "drill",
       "dateLearnt": "Jan 2017",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/3013",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Pea in the F-Hole",
       "type": "Jig",
       "musicKey": "A",
       "era": "",
       "composer": "Natalie Haas",
       "stage": "enhance",
       "dateLearnt": "Jan 2017",
       "video": "",
       "video2": "",
       "source": "Natalie Haas",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Soggy's Slipjig",
       "type": "Slipjig",
       "musicKey": "A",
       "era": "",
       "composer": "Sean Og Graham",
       "stage": "perform",
       "dateLearnt": "Jan 2017",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/9196",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "St Patrick's",
       "type": "An Dro",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "embellish",
       "dateLearnt": "Jan 2017",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Temple Hill",
       "type": "reel",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "Jan 2017",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/2626",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Will There Be Snow in Weed?",
       "type": "Jig",
       "musicKey": "Gm",
       "era": "",
       "composer": "it me",
       "stage": "drill",
       "dateLearnt": "Dec 2016",
       "video": "",
       "video2": "",
       "source": "it me",
       "dots": "Noteflight",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Two Fifty to Vigo",
       "type": "reel",
       "musicKey": "Bm",
       "era": "",
       "composer": "Angus Grant",
       "stage": "drill",
       "dateLearnt": "Nov 2016",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/2711",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Captain O'Kane",
       "type": "Air",
       "musicKey": "Gm",
       "era": "",
       "composer": "O'Carolan",
       "stage": "perform",
       "dateLearnt": "June 2016",
       "video": "",
       "video2": "",
       "source": "",
       "dots": "https://thesession.org/tunes/858",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Archibald MacDonald of Keppoch",
       "type": "Air",
       "musicKey": "Dm",
       "era": "",
       "composer": "John Cunningham",
       "stage": "drill",
       "dateLearnt": "2016",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/6999",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Calliope House",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "2016",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/15",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Doireann's Waltz",
       "type": "Waltz",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "2016",
       "video": "",
       "video2": "",
       "source": "Solas",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Gallowglass",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "2016",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/1369",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Killarney Boys of Pleasure",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "2016",
       "video": "",
       "video2": "",
       "source": "Alasdair Fraser",
       "dots": "https://thesession.org/tunes/733",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Little Star (Mi Pequena Estrella)",
       "type": "Waltz",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "2016",
       "video": "",
       "video2": "",
       "source": "Solas",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Banish Misfortune",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/9",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Banshee, The",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/8",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Ben Kiely's Delight",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/1130",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Black Rogue",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/1076",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Butlers of Glen Avenue",
       "type": "Jig",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "Lunasa",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/820",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Butterfly",
       "type": "Slipjig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Secret of Roan Inish and Bothy Band",
       "dots": "https://thesession.org/tunes/10",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Cliffs of Moher",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/12",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Connaughtman’s Rambles",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/19",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Cooley's",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/1",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Crested Hens",
       "type": "Waltz",
       "musicKey": "Bm",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Nancy",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Cup of Tea",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/20",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Drowsy Maggie",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/27",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Farewell to Ireland",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "0",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "",
       "sessions": "Susan Burke",
       "notes": "Note Kevin's differences in C and D part"
     },
     {
       "flags": "⭐",
       "name": "Gravel Walk",
       "type": "reel",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/42",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Grey Cairn",
       "type": "Jig",
       "musicKey": "Em",
       "era": "80s",
       "composer": "Chris Caswell & Danny Carnahan",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Deb Honeymuller",
       "dots": "https://thesession.org/tunes/15625",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Haste to the Wedding",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/582",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Hiudi Gallagher",
       "type": "Jig",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/810",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "I Buried Me Wife and Danced on Her Grave",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dervish",
       "dots": "https://thesession.org/tunes/383",
       "sessions": "",
       "notes": "or is it frieze britches?"
     },
     {
       "flags": "",
       "name": "Josefin's Waltz",
       "type": "Waltz",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/1016",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Kesh, The",
       "type": "Jig",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/55",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Kid on the Mountain",
       "type": "Slipjig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/52",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Killavil",
       "type": "Jig",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/667",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Knocknagow",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Brendan Fitzgerald",
       "dots": "https://thesession.org/tunes/3354",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Lark in the Morning",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/62",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Lilting Banshee",
       "type": "Jig",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/60",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Maid Behind the Bar",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/64",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Maids of Mitchelstown",
       "type": "reel",
       "musicKey": "Dm",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/120",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Miller's Maggot",
       "type": "Jig",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Solas",
       "dots": "https://thesession.org/tunes/333",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐",
       "name": "Mist-Covered Mountain",
       "type": "Jig",
       "musicKey": "Dm",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "",
       "dots": "https://thesession.org/tunes/256",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Morrison's",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "embellish",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/71",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "My Darling Asleep",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/76",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Orphan",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/217",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Out on the Ocean",
       "type": "Jig",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/108",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Road to Lisdoonvarna",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Deb Honeymuller",
       "dots": "https://thesession.org/tunes/250",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Rose in the Heather",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/447",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Running for the Ferry",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/13050",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Scully's / Scollay's",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/6463",
       "sessions": "",
       "notes": "Shetland variant of \"King of the Fairies\"?"
     },
     {
       "flags": "",
       "name": "Scully Casey's Jig",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Burren Band",
       "dots": "https://thesession.org/tunes/770",
       "sessions": "",
       "notes": "aka Palm Sunday, a slide"
     },
     {
       "flags": "",
       "name": "Stan Chapman's",
       "type": "Jig",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Solas",
       "dots": "https://thesession.org/tunes/324",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Swallowtail",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "perform",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "",
       "sessions": "",
       "notes": "don't be boring"
     },
     {
       "flags": "",
       "name": "Tar Road to Sligo",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Bothy Band",
       "dots": "https://thesession.org/tunes/151",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Tobin’s Favorite",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/308",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "White Petticoat",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "0",
       "video": "",
       "video2": "",
       "source": "Solas / Patrick Street",
       "dots": "https://thesession.org/tunes/332",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "St-Côme No. 1",
       "type": "reel",
       "musicKey": "D/G",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Oct 2017",
       "video": "André Brunet",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": "From Éric Beaudry's grandfather's recordings"
     },
     {
       "flags": "🌙",
       "name": "Brenda Stubbert's",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "Jerry Holland",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "VOM - Big Jams",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙",
       "name": "Dinkie Dorrian's",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "VOM - Big Jams",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙",
       "name": "Frank's Reel",
       "type": "reel",
       "musicKey": "",
       "era": "80s-90s",
       "composer": "John McCusker",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "VOM - Big Jams",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "Le reel à Jules Verret",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "Bottine Souriante?",
       "stage": "drill",
       "dateLearnt": "Oct 2017",
       "video": "La Bottine Souriante",
       "video2": "",
       "source": "La Bottine Souriante",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Douce Plouie de Soir",
       "type": "",
       "musicKey": "",
       "era": "contemp",
       "composer": "André Brunet",
       "stage": "embellish",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Son of a Bear",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "Valse du Chef de Gare / Station Master's Waltz",
       "type": "Waltz",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "André Brunet",
       "video2": "Celtic Fiddle Festival",
       "source": "André Brunet",
       "dots": "",
       "sessions": "Quebecois",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "Le Pointe-au-Pic",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "André Brunet",
       "video2": "",
       "source": "André Brunet",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "Le Printemps",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "André Brunet",
       "video2": "",
       "source": "André Brunet",
       "dots": "",
       "sessions": "Quebecois",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Touch Me If You Dare",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "The Gloaming",
       "dots": "https://thesession.org/tunes/596",
       "sessions": "",
       "notes": "played behind The Pilgrim's Song by The Gloaming"
     },
     {
       "flags": "⭐🔥",
       "name": "A Stór mo Chroí",
       "type": "Air",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Fergal Scahill",
       "video2": "Lillis Ó Laoire (song)",
       "source": "Fergal Scahill",
       "dots": "https://thesession.org/tunes/5737",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "After Dawning",
       "type": "Air",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Cran",
       "video2": "",
       "source": "Cran via Dad",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Bag of Spuds",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Liz Carroll",
       "video2": "Session",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/579",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "⭐🕒",
       "name": "Blackbird",
       "type": "Hornpipe",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/1996",
       "sessions": "",
       "notes": "The first of Kevin's \"The Blackbird (Two Versions)\""
     },
     {
       "flags": "",
       "name": "Bonnie Kate",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/754",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Boys of Ballisodare",
       "type": "Slipjig",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Chieftains",
       "dots": "https://thesession.org/tunes/1340",
       "sessions": "",
       "notes": "Woven into Chieftains' Rocky Road to Dublin"
     },
     {
       "flags": "",
       "name": "Castle Kelly",
       "type": "reel",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/21",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Cathal McConnell's",
       "type": "Jig",
       "musicKey": "Bm",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Lunasa",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/93",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Coleman's Cross",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Bothy Band",
       "dots": "https://thesession.org/tunes/1706",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Corney is Coming",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Finn Magill",
       "video2": "",
       "source": "Finn Magill",
       "dots": "https://thesession.org/tunes/943",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Davey's",
       "type": "reel",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Dervish",
       "video2": "",
       "source": "Dervish",
       "dots": "https://thesession.org/tunes/7792",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Doctor Gilbert",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/129",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Fisherman's Lilt",
       "type": "reel",
       "musicKey": "C/D",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Bothy Band",
       "dots": "https://thesession.org/tunes/345",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Promenade a Monaco",
       "type": "",
       "musicKey": "",
       "era": "contemp",
       "composer": "André Brunet",
       "stage": "perform",
       "dateLearnt": "August 2017",
       "video": "",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "La Rachoudine",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "André Brunet",
       "video2": "",
       "source": "Back Porch Swing",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⚜️",
       "name": "Fleur de Mandragore",
       "type": "reel",
       "musicKey": "A",
       "era": "",
       "composer": "Michel Bordeleau",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "Lunasa",
       "video2": "",
       "source": "Lunasa",
       "dots": "https://thesession.org/tunes/731",
       "sessions": "",
       "notes": "1st of Meitheabh by Lunasa"
     },
     {
       "flags": "🌙⚜️",
       "name": "Untitled Erskine Morris",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "Erskine Morris?",
       "stage": "enhance",
       "dateLearnt": "Sept 2017",
       "video": "André Brunet",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": "Gaspé region"
     },
     {
       "flags": "🌙⚜️",
       "name": "Unknown André St-Côme No. 1 Set #2",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Oct 2017",
       "video": "André Brunet",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🌙⚜️",
       "name": "Unknown André St-Côme No. 1 Set #3",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "drill",
       "dateLearnt": "Oct 2017",
       "video": "André Brunet",
       "video2": "",
       "source": "VOM - André",
       "dots": "",
       "sessions": "",
       "notes": "3 parter? where's it supposed to start?"
     },
     {
       "flags": "🌙⚜️",
       "name": "Reel à Toto",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "André Brunet",
       "video2": "",
       "source": "VOM - André",
       "dots": "https://static1.squarespace.com/static/54ac7644e4b041b86b0bbb16/t/556c9bc8e4b0c962417454ca/1433181128037/Reel+a_+Belze_buth.pdf",
       "sessions": "",
       "notes": "aka Reel à Belzebuth"
     },
     {
       "flags": "",
       "name": "Ghost, The",
       "type": "Three-Two",
       "musicKey": "F",
       "era": "",
       "composer": "Liz Carroll",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Liz Carroll",
       "dots": "https://thesession.org/tunes/13880",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Happy Days of Youth",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Bua",
       "video2": "",
       "source": "Bua",
       "dots": "https://thesession.org/tunes/1669",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Jenny's Welcome to Charlie",
       "type": "reel",
       "musicKey": "Dm",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "Fergal Scahill",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/370",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Katy is Waiting",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Patrick Street",
       "dots": "https://thesession.org/tunes/3239",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Kerry",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Patrick Street",
       "dots": "https://thesession.org/tunes/587",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "King of the Fairies",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/475",
       "sessions": "",
       "notes": "Irish version of \"Scollay's\"; Reel? Hornpipe? generic 4/4 set dance?"
     },
     {
       "flags": "",
       "name": "Lament for Limerick",
       "type": "Air",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Martin Hayes",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Laurel Tree",
       "type": "reel",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Bothy Band",
       "dots": "https://thesession.org/tunes/883",
       "sessions": "",
       "notes": "aka (Liz Carroll calls it) Lost Indian"
     },
     {
       "flags": "",
       "name": "Long Bow Jig, The",
       "type": "Jig",
       "musicKey": "Em",
       "era": "",
       "composer": "Liz Carroll",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Liz Carroll",
       "dots": "https://thesession.org/tunes/1543",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Lord Gordon's Reel",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/1774",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Lucky in Love",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Bua",
       "video2": "",
       "source": "Finn Magill",
       "dots": "https://thesession.org/tunes/1625",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Man of the House",
       "type": "reel",
       "musicKey": "Em",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/222",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "Maudabawn Chapel",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "Ed Reavy",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/302",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "🕒",
       "name": "McFadden's Handsome Daughter",
       "type": "reel",
       "musicKey": "A",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Kevin Burke",
       "video2": "",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/1581",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Michael Kennedy's",
       "type": "reel",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/551",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Musical Priest",
       "type": "reel",
       "musicKey": "Bm",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Dad",
       "dots": "https://thesession.org/tunes/73",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Old Bush Reel",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Paddy Fahey’s",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Dervish",
       "video2": "",
       "source": "Dervish",
       "dots": "https://thesession.org/tunes/150",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Patsy Geary's",
       "type": "Jig",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Bothy Band",
       "dots": "https://thesession.org/tunes/325",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Roscommon Reel",
       "type": "reel",
       "musicKey": "Ed",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Dervish",
       "dots": "https://thesession.org/tunes/637",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "⭐🕒",
       "name": "Scatter the Mud",
       "type": "Jig",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Lunasa",
       "video2": "",
       "source": "Lunasa",
       "dots": "https://thesession.org/tunes/728",
       "sessions": "",
       "notes": "1st of Márta by Lunasa, but see Kevin's version"
     },
     {
       "flags": "",
       "name": "Sean Ryan's",
       "type": "Jig",
       "musicKey": "Am",
       "era": "",
       "composer": "",
       "stage": "enhance",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Martin Hayes",
       "dots": "https://thesession.org/tunes/273",
       "sessions": "",
       "notes": "aka The Castle?"
     },
     {
       "flags": "",
       "name": "Sliabh Russell",
       "type": "Jig",
       "musicKey": "Ad",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Lunasa",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/335",
       "sessions": "Susan Burke",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Star Above the Garter, The",
       "type": "Slide",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "Sessions",
       "dots": "https://thesession.org/tunes/1398",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Táimse im Choladh",
       "type": "Air",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "",
       "video2": "",
       "source": "The Session",
       "dots": "https://thesession.org/tunes/6944",
       "sessions": "",
       "notes": "I Am Asleep"
     },
     {
       "flags": "",
       "name": "The Duke Of Leinster",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Session",
       "video2": "",
       "source": "Internet",
       "dots": "",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Tomeen O’Dea’s",
       "type": "reel",
       "musicKey": "G",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Dervish",
       "video2": "",
       "source": "Dervish",
       "dots": "https://thesession.org/tunes/1986",
       "sessions": "",
       "notes": ""
     },
     {
       "flags": "",
       "name": "Toss the Feathers",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Kevin Burke",
       "video2": "Fergal Scahill",
       "source": "Kevin Burke",
       "dots": "https://thesession.org/tunes/113",
       "sessions": "Susan Burke?",
       "notes": "West Clare version?"
     },
     {
       "flags": "",
       "name": "Wedding Reel",
       "type": "reel",
       "musicKey": "D",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Fergal Scahill",
       "video2": "",
       "source": "Lunasa",
       "dots": "https://thesession.org/tunes/518",
       "sessions": "",
       "notes": "aka Miss MacLeod’s Farewell To Chastity"
     },
     {
       "flags": "⭐🕒",
       "name": "Wee Bag of Spuds",
       "type": "reel",
       "musicKey": "",
       "era": "",
       "composer": "",
       "stage": "learn",
       "dateLearnt": "",
       "video": "Seamus Egan",
       "video2": "",
       "source": "Seamus Egan",
       "dots": "",
       "sessions": "",
       "notes": ""
     }
    ].forEach(tune => {
        console.log(tune)
        pushNewTune(tune)
    })
}
